import { createFileRoute } from "@tanstack/react-router";
import { Bot, Camera, CameraOff, ChevronRight, Copy, Link2, Mic, MicOff, MonitorUp, PhoneOff, Search, Send, Settings, Users, X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { stemTools } from "@/lib/stem-tools";

export const Route = createFileRoute("/aulas")({
  head: () => ({ meta: [{ title: "Sala de clase — Nexo STEM" }, { name: "description", content: "Aula virtual con videollamada, chat y herramientas STEM compartidas." }, { property: "og:title", content: "Sala de clase — Nexo STEM" }, { property: "og:description", content: "Clases tecnológicas en vivo con recursos interactivos." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: ClassroomPage,
});

function ClassroomPage() {
  const [mic, setMic] = useState(true);
  const [camera, setCamera] = useState(true);
  const [chatOpen, setChatOpen] = useState(true);
  const [toolOpen, setToolOpen] = useState(false);
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState([{ author: "Lucas", text: "¡Ya conecté el sensor!", time: "10:34" }, { author: "Ana", text: "¿Compartimos el circuito?", time: "10:35" }]);
  const [sharedTool, setSharedTool] = useState("Playtecduino");
  const sendMessage = () => { if (!message.trim()) return; setMessages([...messages, { author: "María Profe", text: message.trim(), time: "Ahora" }]); setMessage(""); };

  return <div className="flex min-h-[calc(100vh-4rem)] flex-col bg-classroom text-classroom-foreground">
    <header className="flex flex-wrap items-center gap-3 border-b border-classroom-border px-4 py-3 md:px-6"><div><p className="text-xs text-classroom-muted">CLASE EN VIVO · 00:38:12</p><h1 className="font-display text-base font-extrabold">Laboratorio de sensores</h1></div><div className="ml-auto flex items-center gap-2"><span className="hidden items-center gap-1 text-xs text-classroom-muted sm:flex"><Users className="size-4" />18 participantes</span><Button variant="outline" size="sm" className="border-classroom-border bg-transparent text-classroom-foreground hover:bg-classroom-panel hover:text-classroom-foreground" onClick={() => navigator.clipboard?.writeText("NEXO-8432")}><Copy />NEXO-8432</Button><Button variant="ghost" size="icon" className="text-classroom-foreground hover:bg-classroom-panel"><Settings /></Button></div></header>
    <div className="relative flex min-h-0 flex-1">
      <main className="flex min-w-0 flex-1 flex-col p-3 md:p-5"><div className="grid min-h-0 flex-1 grid-cols-2 gap-3 lg:grid-cols-3"><VideoTile name="María Profe" role="Docente" accent /><VideoTile name="Lucas" role="Estudiante" /><VideoTile name="Ana" role="Estudiante" /><VideoTile name="Mateo" role="Estudiante" /><div className="hidden lg:block"><VideoTile name="Valentina" role="Estudiante" /></div><div className="grid place-items-center rounded-md border border-classroom-border bg-classroom-panel"><div className="text-center"><span className="grid size-14 place-items-center rounded-full bg-primary font-bold text-primary-foreground">+13</span><p className="mt-3 text-sm text-classroom-muted">Más estudiantes</p></div></div></div>
        <div className="mt-4 flex items-center justify-center gap-2"><Button size="icon" className={mic ? "bg-classroom-panel text-classroom-foreground hover:bg-classroom-border" : "bg-destructive text-destructive-foreground"} onClick={() => setMic(!mic)} aria-label={mic ? "Silenciar micrófono" : "Activar micrófono"}>{mic ? <Mic /> : <MicOff />}</Button><Button size="icon" className={camera ? "bg-classroom-panel text-classroom-foreground hover:bg-classroom-border" : "bg-destructive text-destructive-foreground"} onClick={() => setCamera(!camera)} aria-label={camera ? "Apagar cámara" : "Encender cámara"}>{camera ? <Camera /> : <CameraOff />}</Button><Button className="bg-primary text-primary-foreground" onClick={() => setToolOpen(!toolOpen)}><MonitorUp />Compartir herramienta</Button><Button size="icon" className="bg-destructive text-destructive-foreground hover:bg-destructive/90" aria-label="Salir de la sala"><PhoneOff /></Button><Button size="icon" className="bg-classroom-panel text-classroom-foreground hover:bg-classroom-border md:hidden" onClick={() => setChatOpen(!chatOpen)} aria-label="Abrir chat"><Send /></Button></div>
      </main>
      {chatOpen && <aside className="absolute inset-y-0 right-0 z-20 flex w-[min(88vw,340px)] flex-col border-l border-classroom-border bg-classroom-panel md:relative"><div className="flex items-center border-b border-classroom-border p-4"><div><h2 className="font-display font-extrabold">Chat de la clase</h2><p className="text-xs text-classroom-muted">Mensajes sincronizados</p></div><Button variant="ghost" size="icon" className="ml-auto text-classroom-foreground hover:bg-classroom-border md:hidden" onClick={() => setChatOpen(false)}><X /></Button></div><div className="flex-1 space-y-4 overflow-y-auto p-4">{messages.map((item, index) => <div key={`${item.author}-${index}`} className={item.author === "María Profe" ? "ml-8" : "mr-8"}><div className="mb-1 flex items-center gap-2 text-xs"><strong>{item.author}</strong><span className="text-classroom-muted">{item.time}</span></div><p className={`rounded-md p-3 text-sm ${item.author === "María Profe" ? "bg-primary text-primary-foreground" : "bg-classroom-border"}`}>{item.text}</p></div>)}</div><div className="flex gap-2 border-t border-classroom-border p-3"><Input value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => event.key === "Enter" && sendMessage()} placeholder="Escribe un mensaje" className="border-classroom-border bg-classroom text-classroom-foreground" /><Button size="icon" onClick={sendMessage} aria-label="Enviar mensaje"><Send /></Button></div></aside>}
      {toolOpen && <div className="absolute bottom-20 left-1/2 z-30 w-[min(92vw,560px)] -translate-x-1/2 rounded-md border border-classroom-border bg-background p-4 text-foreground shadow-2xl"><div className="flex items-center"><div><h2 className="font-display font-extrabold">Proyectar una herramienta</h2><p className="text-xs text-muted-foreground">Todos verán el recurso seleccionado.</p></div><Button variant="ghost" size="icon" className="ml-auto" onClick={() => setToolOpen(false)}><X /></Button></div><div className="relative mt-4"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" placeholder="Buscar en el catálogo" /></div><div className="mt-3 max-h-56 space-y-1 overflow-y-auto">{stemTools.slice(0, 6).map((tool) => <button key={tool.id} onClick={() => { setSharedTool(tool.name); setToolOpen(false); }} className="flex w-full items-center gap-3 rounded-md p-3 text-left hover:bg-accent"><span className="grid size-9 place-items-center rounded-md bg-cyan-soft"><Bot className="size-4" /></span><span><strong className="block text-sm">{tool.name}</strong><span className="text-xs text-muted-foreground">{tool.technology}</span></span><ChevronRight className="ml-auto size-4" /></button>)}</div></div>}
    </div>
    <div className="pointer-events-none fixed bottom-3 left-3 z-30 hidden items-center gap-2 rounded-md bg-cyan-soft px-3 py-2 text-xs font-bold text-foreground lg:flex"><Link2 className="size-4" />Proyectando: {sharedTool}</div>
  </div>;
}

function VideoTile({ name, role, accent = false }: { name: string; role: string; accent?: boolean }) {
  const initials = name.split(" ").map((part) => part[0]).join("").slice(0, 2);
  return <div className={`relative min-h-40 overflow-hidden rounded-md border ${accent ? "border-primary" : "border-classroom-border"} bg-classroom-panel`}><div className="grid h-full place-items-center"><span className={`grid size-16 place-items-center rounded-full text-lg font-extrabold ${accent ? "bg-primary text-primary-foreground" : "bg-classroom-border"}`}>{initials}</span></div><div className="absolute inset-x-0 bottom-0 flex items-center justify-between bg-classroom/80 px-3 py-2 backdrop-blur"><span><strong className="block text-xs">{name}</strong><span className="block text-[10px] text-classroom-muted">{role}</span></span><Mic className="size-3 text-success" /></div></div>;
}