import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, Blocks, Bot, Box, Code2, Gamepad2, Search, Shapes, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ageGroups, categories, stemTools, type AgeGroup, type StemTool } from "@/lib/stem-tools";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/herramientas")({
  head: () => ({ meta: [{ title: "Herramientas STEM — Nexo STEM" }, { name: "description", content: "Explora herramientas de programación, robótica, diseño 3D y evaluación por edad." }, { property: "og:title", content: "Centro de Herramientas STEM" }, { property: "og:description", content: "Recursos educativos seleccionados para crear, programar y experimentar." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: ToolsPage,
});

const toolIcons = [Code2, Gamepad2, Bot, Box, Shapes, Blocks];

function ToolsPage() {
  const [search, setSearch] = useState("");
  const [age, setAge] = useState<AgeGroup | "Todas">("Todas");
  const [category, setCategory] = useState<(typeof categories)[number]>("Todas");
  const [selected, setSelected] = useState<StemTool | null>(null);
  const filtered = useMemo(() => stemTools.filter((tool) => (age === "Todas" || tool.ages.includes(age)) && (category === "Todas" || tool.category === category) && `${tool.name} ${tool.technology}`.toLowerCase().includes(search.toLowerCase())), [age, category, search]);

  return <div className="mx-auto max-w-7xl px-4 py-8 md:px-8 md:py-10">
    <section className="flex flex-col gap-5 border-b border-border pb-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="flex items-center gap-2 text-sm font-bold text-primary"><Sparkles className="size-4" />Explora, juega y aprende</p><h1 className="mt-2 text-3xl font-extrabold md:text-5xl">Centro de Herramientas STEM</h1><p className="mt-3 max-w-2xl text-muted-foreground">Una colección segura de experiencias para desarrollar pensamiento lógico, creatividad y habilidades tecnológicas.</p></div><div className="relative w-full lg:max-w-sm"><Search className="absolute left-3 top-3 size-5 text-muted-foreground" /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por nombre o tecnología" className="h-11 bg-card pl-10" /></div></section>
    <section className="py-6"><p className="mb-3 text-xs font-extrabold uppercase text-muted-foreground">Elige una etapa</p><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-6"><button onClick={() => setAge("Todas")} className={cn("rounded-md border p-3 text-left transition-colors", age === "Todas" ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card hover:bg-accent")}><strong className="block text-sm">Todas</strong><span className="text-xs opacity-70">4–17 años</span></button>{ageGroups.map((group) => <button key={group.name} onClick={() => setAge(group.name)} className={cn("rounded-md border p-3 text-left transition-colors", age === group.name ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card hover:bg-accent")}><strong className="block text-sm">{group.name}</strong><span className="text-xs opacity-70">{group.range}</span></button>)}</div></section>
    <div className="flex gap-2 overflow-x-auto border-y border-border py-3">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={cn("shrink-0 rounded-md px-3 py-2 text-sm font-bold", category === item ? "bg-foreground text-background" : "bg-card text-muted-foreground hover:bg-accent")}>{item}</button>)}</div>
    <div className="mb-4 mt-7 flex items-center justify-between"><h2 className="text-xl font-extrabold">{category}</h2><span className="text-sm text-muted-foreground">{filtered.length} recursos</span></div>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((tool, index) => { const Icon = toolIcons[index % toolIcons.length] ?? Code2; return <article key={tool.id} className="group flex min-h-64 flex-col rounded-md border border-border bg-card p-5 transition-[transform,box-shadow] hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between"><span className={cn("grid size-12 place-items-center rounded-md", index % 3 === 0 ? "bg-orange-soft" : index % 3 === 1 ? "bg-cyan-soft" : "bg-violet-soft")}><Icon className="size-6" /></span><span className={cn("rounded-md px-2 py-1 text-[11px] font-extrabold", tool.difficulty === "Básico" ? "bg-cyan-soft" : tool.difficulty === "Intermedio" ? "bg-orange-soft" : "bg-violet-soft")}>{tool.difficulty}</span></div><p className="mt-5 text-xs font-bold uppercase text-primary">{tool.technology}</p><h3 className="mt-1 text-xl font-extrabold">{tool.name}</h3><p className="mt-2 flex-1 text-sm leading-relaxed text-muted-foreground">{tool.description}</p><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="text-xs font-bold text-muted-foreground">{tool.ageLabel}</span><Button variant="ghost" size="sm" onClick={() => setSelected(tool)}>Abrir <ArrowUpRight /></Button></div></article>; })}</section>
    {filtered.length === 0 && <div className="py-20 text-center"><Search className="mx-auto size-8 text-muted-foreground" /><h3 className="mt-4 font-extrabold">No encontramos coincidencias</h3><p className="text-sm text-muted-foreground">Prueba con otro término o cambia los filtros.</p></div>}
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-w-3xl overflow-hidden p-0"><div className="bg-primary p-6 text-primary-foreground"><p className="text-xs font-bold uppercase opacity-75">{selected?.category}</p><DialogHeader><DialogTitle className="mt-2 text-2xl">{selected?.name}</DialogTitle><DialogDescription className="text-primary-foreground/80">{selected?.description}</DialogDescription></DialogHeader></div><div className="p-6"><div className="grid min-h-48 place-items-center rounded-md border border-dashed border-border bg-muted text-center"><div><Blocks className="mx-auto size-10 text-primary" /><p className="mt-3 font-bold">Lista para empezar</p><p className="mt-1 text-sm text-muted-foreground">La herramienta se abrirá en una nueva pestaña segura.</p></div></div><Button className="mt-5 w-full" onClick={() => selected && window.open(selected.url, "_blank", "noopener,noreferrer")}>Lanzar {selected?.name}<ArrowUpRight /></Button></div></DialogContent></Dialog>
  </div>;
}